apiVersion: v1
kind: ConfigMap
metadata:
  name: kiii-project-config
  namespace: kiii
data:
  FRONTEND_URL: "http://frontend:5173"
  BACKEND_URL: "http://backend:3000"

---

apiVersion: v1
kind: Secret
metadata:
  name: kiii-project-secrets
  namespace: kiii
type: Opaque
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbkBteWNsdXN0ZXIuZnFpZGUubW9uZ29kYi5uZXQ=
  MONGO_DB_NAME: Tm9kZS1BUEk=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: kiii
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: kiii-proekt
        image: ppucoski/kiiiproject-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: kiii-project-secrets
              key: MONGO_URL
        - name: MONGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: kiii-project-secrets
              key: MONGO_DB_NAME
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              name: kiii-project-config
              key: FRONTEND_URL
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kiii
spec:
  replicas:  2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: kiii-proekt
        image: ppucoski/kiiiproject-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: kiii-project-config
              key: BACKEND_URL