name: CI

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend  
          file: ./backend/Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kiiiproject-backend:latest

     
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend 
          file: ./frontend/Dockerfile  
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kiiiproject-frontend:latest
